# Generated by Django 4.2.1 on 2023-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_complete_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(default='price_id_default', max_length=200),
            preserve_default=False,
        ),
    ]
